### ISSUE TITLE
BacktraceMetrics constructor can result in un-catchable promise rejection

### ISSUE THREAD

**Issue by Mike-Bell** [backtrace-labs/backtrace-js#23]
We've seen a few times in our backtrace logs where this function can result in an unhandled promise (specifically if the backtrace server hiccups and gives us a 502). This seems to come from here: https://github.com/backtrace-labs/backtrace-js/blob/66b477778ab97ac7f15a362b88805cc7e6b6b546/source/model/backtraceMetrics.ts#L68

This is pretty inconvenient for us, since we have to go out of our way to implement special logic in our promise rejection handler to filter out this error.

**Comment by konraddysput** [comment]
hi @Mike-Bell 

Thank you for posting this issue. I see that when the response from the server is different than ok, the util method rejects the promise that is not handled anywhere else. You can expect more information about library changes/updates soon. 

Thank you

**Comment by konraddysput** [comment]
hi @Mike-Bell 

The issue should be fixed in the next backtrace-js update. I also attached the pull request with the fix to this issue. 

Thank you!

**Comment by konraddysput** [comment]
hi @Mike-Bell . The new version of the backtrace-js library with the fix for this issue has been released. I'm closing the issue now, but feel free to reopen it if you still have a problem with types. 

Thank you once again for your collaboration!
