### ISSUE TITLE
Types are missing

### ISSUE THREAD

**Issue by Mike-Bell** [backtrace-labs/backtrace-js#24]
![image](https://user-images.githubusercontent.com/8780033/174094974-e9844e49-c7d3-4049-bb19-b831a917ac51.png)

**Comment by konraddysput** [comment]
hi @Mike-Bell . Thank you for the information. The problem was addressed in the pull request that I added to this issue. You can expect the update really soon.

**Comment by konraddysput** [comment]
hi @Mike-Bell . The new version of the backtrace-js library with the fix for this issue has been released. I'm closing the issue now, but feel free to reopen it if you still have a problem with types. 

Thank you once again for your collaboration!
