### ISSUE TITLE
Several types are incorrect

### ISSUE THREAD

**Issue by Mike-Bell** [backtrace-labs/backtrace-js#27]
We have types working now - great! Unfortunately your documentation (and our established usage) fails the type checking. 

`initialize` should accept `Partial<BacktraceClientOptions>`, or some other `type` with everything except `endpoint` being optional, since all other options are, in fact, optional. 

![image](https://user-images.githubusercontent.com/8780033/175003617-a82a996a-a195-4641-9a2f-577483774281.png)

Additionally, the `report` function should take an `Error`. We have long been passing this function an Error object, but that fails type checking. I think the type checking maybe intended to be `arg: (() => void) | Error | string | object` instead of `arg: () => void | Error | string | object`

![image](https://user-images.githubusercontent.com/8780033/175004733-73837cfb-34a6-4290-8930-a075598d33c7.png)

**Comment by perf2711** [comment]
Hey @Mike-Bell, thank you for your submission. I've submitted a PR https://github.com/backtrace-labs/backtrace-js/pull/28 that fixes the changes. As soon as it is merged, we will publish the new version to npm, so you can use it.

We would gladly like your input on this PR! If you see any more issues, let us know.

**Comment by konraddysput** [comment]
hi @Mike-Bell!

I just wanted to let you know that the backtrace-js library with fixes for this issue is available on npm! Please let us know if you have any problems and feel free to reopen the issue if you still experience issues.
