### ISSUE TITLE
JS file says version 0.0.6 when release says 0.0.10

### ISSUE THREAD

**Issue by elayman** [backtrace-labs/backtrace-js#9]
https://github.com/backtrace-labs/backtrace-js/blob/df41b1be09c3f051e2112a7e9b8070eff45e1fb3/lib/index.js#L5

Not sure if this causes any problems.

**Comment by amadden80** [comment]
Thank you for this!

**Comment by amadden80** [comment]
This will be resolved with the release of 0.0.11
